# -*- coding: utf-8 -*-
"""assingment 2 pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zwqeAw4aMzRY8wHYCdibf_KMC5q4Jchk
"""

import pandas as pd

users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep="|", index_col="user_id")
users.head(10)

users.tail(10)

users.shape[0]

users.shape[1]

users.columns

users.index

users.dtypes

users["occupation"]

users["occupation"].value_counts().count()

users["occupation"].value_counts().sort_values(ascending=False).head()

users.describe()

users.describe(include="all")

users.occupation.describe()

users.age.mean()

users.age.value_counts().tail()